### ISSUE TITLE
Array out of bounds: exactly nine ranks

### ISSUE THREAD

**Issue by CurlyBryce** [BlockyBorzan/BlockyRanks#4]
Having exactly nine ranks in a branch with child branches and trying to open the /ranks gui provides an error in the server console on paper/spigot 1.15.2 using BlockyRanks version 1.5.0.  I have tested the issue with 8 and 10 branches both of which work fine and /ranks can execute without errors.  The issue only persists with child branches involved though.  Without any and 9 ranks in a branch the /ranks gui runs without issue.  The error in the console is:
```
[11:19:09 ERROR]: [BlockyRanks] | A critical exception has occured: 
java.lang.ArrayIndexOutOfBoundsException: 21
	at java.util.Arrays$ArrayList.set(Arrays.java:3846)
	at net.minecraft.server.v1_15_R1.NonNullList.set(SourceFile:53)
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:108)
	at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftInventory.setItem(CraftInventory.java:99)
	at me.blocky.ranks.gui.ranks.RanksGuiHandler.buildBranchInventories(RanksGuiHandler.java:283)
	at me.blocky.ranks.listener.RanksListener.lambda$getInv$0(RanksListener.java:275)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at me.blocky.ranks.listener.RanksListener.getInv(RanksListener.java:275)
	at me.blocky.ranks.listener.RanksListener.startListening(RanksListener.java:142)
	at me.blocky.ranks.listener.RanksListener.initializeAndStart(RanksListener.java:50)
	at me.blocky.ranks.gui.ranks.RanksGuiHandler.showRanks(RanksGuiHandler.java:104)
	at me.blocky.ranks.command.RanksCommand.parseCommand(RanksCommand.java:91)
	at me.blocky.ranks.lib.command.PlayerCommand.execute(PlayerCommand.java:31)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742)
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1820)
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628)
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
	at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by CurlyBryce** [comment]
After some more testing it turns out to be any multiple of nine ranks with a child branch not just nine in particular.

**Comment by BlockyBorzan** [comment]
Hi,

Thank you for the issue report. I will investigate this bug. 
Probably an off-by-one error on my part. 

Cheers,
Blocky

**Comment by BlockyBorzan** [comment]
The issue will be fixed with the next update. Thank you for the report!
