### ISSUE TITLE
Server unable to load

### ISSUE THREAD

**Issue by kairizal805** [BlockyBorzan/BlockyRanks#9]
I keep getting this error and a longer string of errors whenever we have our daily restarts. 

[14:19:27 ERROR]: [BlockyRanks] | Command was issued but no blockyranks configuration was found for this world.
[14:19:27 ERROR]: [BlockyRanks] | A critical exception has occured:
java.lang.NullPointerException
at me.blocky.ranks.listener.RanksListener.<init>(RanksListener.java:117)
at me.blocky.ranks.listener.RanksListener.initializeAndStart(RanksListener.java:48)
at me.blocky.ranks.gui.ranks.RanksGuiHandler.showRanks(RanksGuiHandler.java:95)
at me.blocky.ranks.command.RanksCommand.parsePlayerCommand(RanksCommand.java:79)
at me.blocky.ranks.lib.command.PlayerCommand.parseCommand(PlayerCommand.java:20)
at me.blocky.ranks.lib.command.PublicCommand.execute(PublicCommand.java:26)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800)
at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1903)
at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1714)
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by kairizal805** [comment]
[BRanksconfig.txt](https://github.com/BlockyBorzan/BlockyRanks/files/5277892/BRanksconfig.txt)
[BlockyRanks restart error.txt](https://github.com/BlockyBorzan/BlockyRanks/files/5277893/BlockyRanks.restart.error.txt)

**Comment by BlockyBorzan** [comment]
Apologies for taking so long to answer, for some reason, I did not get an Email notification as usual.

I believe your yml is just invalid.

> ...
> initial-branches:
>   "wanderer"
>   all-worlds:
> ...

should be 

> ...
> initial-branches: 
>   all-worlds:
> ...

Check the original file by generating it anew or downloading it from the wiki. 

Cheers,

Blocky
